<?php
/**Cargos comissionados*/
define( "DIRETORDOCENTRO", 1 );
define( "VICEDIRETORDOCENTRO", 2 );
define( "CHEFEDODEPARTAMENTO", 3 );
define( "SUBCHEFEDODEPARTARTAMENTO", 4 );
define( "SECRETARIODOCENTRO", 5 );
define( "CHEFEDEEXPEDIENTE", 6 );
define( "SECRETARIADOCENTRO", 7 );
define( "REITOR", 8 );

/**Status atual do professor*/
define( "EMATIVIDADE", 1 );
define( "AFASTAMENTOPARAPOSDOUTORADO", 2 );
define( "AFASTAMENTOPARADOUTORADO", 3 );
define( "AFASTAMENTOPARAMESTRADO", 4 );
define( "AFASTAMENTODECURTADURACAO", 5 );
define( "LICENCACAPACITACAO", 6 );
define( "LICENCAPARATRATAMENTODESAUDE", 7 );
define( "LICENCAPARATRATARDEASSUNTOSPARTICULARES", 8 );
define( "APOSENTADO", 9 );
define( "CEDIDOPARAOUTROORGAOPUBLICO", 10 );
define( "LOTADOTEMPORARIAMENTEEMOUTRAIFE", 11 );

/**Tipos de afastamento*/
define( "LICENCAPORMOTIVODEDOENCAEMFAMILIA", 1 );
define( "LICENCAPARAATIVIDADEPOLITICA", 2 );
define( "LICENCAPREMIOPORASSIDUIDADE", 3 );
define( "LICENCAAGESTANTEOUAADOTANTE", 4 );
define( "LICENCAPARAMANDATOCLASSISTA", 5 );
define( "LICENCASABATICA", 6 );
define( "AFASTAMENTOPARASERVIREMOUTROORGAOOUINSTITUICAOFEDERALDEENSINOSUPERIOR", 7 );
define( "AFASTAMENTOPARAEXERCICIODEMANDATOELETIVO", 8 );
define( "AFASTAMENTOPARAESTUDOOUMISSAONOEXTERIOR", 9 );
define( "AFASTAMENTOINTEGRALDECURTADURACAOPARAFORMACAONOPAISOUNOEXTERIOR", 10 );
define( "AFASTAMENTOINTEGRALDEMEDIAOULONGADURACAOPARAFORMACAONOPAISOUNOEXTERIOR", 11 );
define( "REDISTRIBUICAO", 15 );
define( "AFASTAMENTOPARCIALPARAFORMACAODOUTORADO", 16 );
define( "AFASTAMENTOPARCIALPARAFORMACAOMESTRADO", 17 );
?>